name: Publish Gem
on:
  push:
    tags:
      - ^[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    needs: [rspec-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Release Gem
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake release